title:              Yang Sag Woo
email:              dndb3599@gmail.com
description:        `2016108271 컴퓨터 공학과 3 학년`
author:             Start Bootstrap
baseurl:            "/blog"
url:                https://https://github.com/IGhost-P/blog.github.io

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
